// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.8
// source: watcher-by-etcd-and-sync-to-other-module/pb/rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEventProto_EventType int32

const (
	WatchEventProto_ET_PUT    WatchEventProto_EventType = 0
	WatchEventProto_ET_DELETE WatchEventProto_EventType = 1
)

// Enum value maps for WatchEventProto_EventType.
var (
	WatchEventProto_EventType_name = map[int32]string{
		0: "ET_PUT",
		1: "ET_DELETE",
	}
	WatchEventProto_EventType_value = map[string]int32{
		"ET_PUT":    0,
		"ET_DELETE": 1,
	}
)

func (x WatchEventProto_EventType) Enum() *WatchEventProto_EventType {
	p := new(WatchEventProto_EventType)
	*p = x
	return p
}

func (x WatchEventProto_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEventProto_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_enumTypes[0].Descriptor()
}

func (WatchEventProto_EventType) Type() protoreflect.EnumType {
	return &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_enumTypes[0]
}

func (x WatchEventProto_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEventProto_EventType.Descriptor instead.
func (WatchEventProto_EventType) EnumDescriptor() ([]byte, []int) {
	return file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescGZIP(), []int{2, 0}
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPrefixes []string `protobuf:"bytes,1,rep,name=key_prefixes,json=keyPrefixes,proto3" json:"key_prefixes,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKeyPrefixes() []string {
	if x != nil {
		return x.KeyPrefixes
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revision    int64    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	KeyPrefixes []string `protobuf:"bytes,2,rep,name=key_prefixes,json=keyPrefixes,proto3" json:"key_prefixes,omitempty"`
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchRequest) GetKeyPrefixes() []string {
	if x != nil {
		return x.KeyPrefixes
	}
	return nil
}

type WatchEventProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     WatchEventProto_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.WatchEventProto_EventType" json:"type,omitempty"`
	Key      string                    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Revision int64                     `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Message  []byte                    `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WatchEventProto) Reset() {
	*x = WatchEventProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventProto) ProtoMessage() {}

func (x *WatchEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventProto.ProtoReflect.Descriptor instead.
func (*WatchEventProto) Descriptor() ([]byte, []int) {
	return file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *WatchEventProto) GetType() WatchEventProto_EventType {
	if x != nil {
		return x.Type
	}
	return WatchEventProto_ET_PUT
}

func (x *WatchEventProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchEventProto) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchEventProto) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto protoreflect.FileDescriptor

var file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x35, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x62, 0x79, 0x2d, 0x65, 0x74, 0x63,
	0x64, 0x2d, 0x61, 0x6e, 0x64, 0x2d, 0x73, 0x79, 0x6e, 0x63, 0x2d, 0x74, 0x6f, 0x2d, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2f, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x65, 0x79,
	0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x6b, 0x65, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x0c,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x65, 0x79, 0x5f,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x6b, 0x65, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x0f,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x09, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x54, 0x5f, 0x50, 0x55,
	0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x01, 0x32, 0x6d, 0x0a, 0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x2e, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x12, 0x32, 0x0a,
	0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x62, 0x79, 0x2d,
	0x65, 0x74, 0x63, 0x64, 0x2d, 0x61, 0x6e, 0x64, 0x2d, 0x73, 0x79, 0x6e, 0x63, 0x2d, 0x74, 0x6f,
	0x2d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescOnce sync.Once
	file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescData = file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDesc
)

func file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescGZIP() []byte {
	file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescOnce.Do(func() {
		file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescData)
	})
	return file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDescData
}

var file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_goTypes = []interface{}{
	(WatchEventProto_EventType)(0), // 0: pb.WatchEventProto.EventType
	(*GetRequest)(nil),             // 1: pb.GetRequest
	(*WatchRequest)(nil),           // 2: pb.WatchRequest
	(*WatchEventProto)(nil),        // 3: pb.WatchEventProto
}
var file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_depIdxs = []int32{
	0, // 0: pb.WatchEventProto.type:type_name -> pb.WatchEventProto.EventType
	1, // 1: pb.Watcher.Get:input_type -> pb.GetRequest
	2, // 2: pb.Watcher.Watch:input_type -> pb.WatchRequest
	3, // 3: pb.Watcher.Get:output_type -> pb.WatchEventProto
	3, // 4: pb.Watcher.Watch:output_type -> pb.WatchEventProto
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_init() }
func file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_init() {
	if File_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchEventProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_goTypes,
		DependencyIndexes: file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_depIdxs,
		EnumInfos:         file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_enumTypes,
		MessageInfos:      file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_msgTypes,
	}.Build()
	File_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto = out.File
	file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_rawDesc = nil
	file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_goTypes = nil
	file_watcher_by_etcd_and_sync_to_other_module_pb_rpc_proto_depIdxs = nil
}
