// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.8
// source: watcher-by-etcd-and-sync-to-other-module/pb/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 年龄
	Age int32 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *UserProto) Reset() {
	*x = UserProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProto) ProtoMessage() {}

func (x *UserProto) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProto.ProtoReflect.Descriptor instead.
func (*UserProto) Descriptor() ([]byte, []int) {
	return file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProto) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_watcher_by_etcd_and_sync_to_other_module_pb_user_proto protoreflect.FileDescriptor

var file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDesc = []byte{
	0x0a, 0x36, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x62, 0x79, 0x2d, 0x65, 0x74, 0x63,
	0x64, 0x2d, 0x61, 0x6e, 0x64, 0x2d, 0x73, 0x79, 0x6e, 0x63, 0x2d, 0x74, 0x6f, 0x2d, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x31, 0x0a, 0x09,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x42,
	0x2d, 0x5a, 0x2b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x62, 0x79, 0x2d, 0x65, 0x74,
	0x63, 0x64, 0x2d, 0x61, 0x6e, 0x64, 0x2d, 0x73, 0x79, 0x6e, 0x63, 0x2d, 0x74, 0x6f, 0x2d, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescOnce sync.Once
	file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescData = file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDesc
)

func file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescGZIP() []byte {
	file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescOnce.Do(func() {
		file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescData)
	})
	return file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDescData
}

var file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_goTypes = []interface{}{
	(*UserProto)(nil), // 0: pb.UserProto
}
var file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_init() }
func file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_init() {
	if File_watcher_by_etcd_and_sync_to_other_module_pb_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_goTypes,
		DependencyIndexes: file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_depIdxs,
		MessageInfos:      file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_msgTypes,
	}.Build()
	File_watcher_by_etcd_and_sync_to_other_module_pb_user_proto = out.File
	file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_rawDesc = nil
	file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_goTypes = nil
	file_watcher_by_etcd_and_sync_to_other_module_pb_user_proto_depIdxs = nil
}
