
kafka:
  brokers: ["localhost:9092"]
  topics: ["alarm-task"]

logging:
  level: debug
  logToStderr: true  # 该值为true时，日志将会打印到标准输出，不会打印到文件，方便本地开发环境调试
  filename: logs/election-by-etcd.log
  maxSize: 100  # MB，单日志文件的最大容量
  maxBackups: 3  # 最大保留的日志文件数量
  maxAge: 7  # Days, 最大保留的日志文件天数